version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      #- "82:80/tcp"
      - "53:53/tcp"
      - "53:53/udp"
      #- "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: 'ouk'
    # Volumes store your data between container upgrades
    volumes:
      - '/home/oukerie/data/pihole/etc-pihole:/etc/pihole'
      - '/home/oukerie/data/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pi.rule=Host(`pi.oukcorp.com`)"
      - "traefik.http.services.pi.loadbalancer.server.port=80"
      - traefik.http.middlewares.pi.redirectregex.regex=^https://pi\.oukcorp\.com/$$
      - "traefik.http.middlewares.pi.redirectregex.replacement=https://pi.oukcorp.com/admin/"
      - traefik.http.routers.pi.middlewares=pi

      

networks:
  default:
    external:
      name: traefik