version: "3.3"


# https://doc.traefik.io/traefik/https/acme/
# https://community.cloudflare.com/t/i-need-cf-zone-api-token-for-traefik-setting-but-dont-know-how-create-it/418006


services:

  traefik:
    image: "traefik/traefik:experimental-master"
    container_name: "traefik"

    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/etc/traefik/traefik.yml"
      - "/home/oukerie/data/letsencrypt:/letsencrypt"

    env_file:
      - .env

    restart: "unless-stopped"

    labels:
      traefik.enable: 'true'
      traefik.http.routers.traefik-dashboard-http-router.entrypoints: secure
      traefik.http.routers.traefik-dashboard-http-router.rule: Host(`traefik.oukcorp.com`)
      traefik.http.routers.traefik-dashboard-http-router.service: api@internal


networks:
  default:
    external:
      name: traefik
