- Oukflix Download:
    - Sonarr:
        icon: sonarr.png
        href: https://sonarr.oukcorp.com/
        description: Series management
        ping: http://sonarr:8989
        container: sonarr
        widget:
          type: sonarr
          url: http://sonarr:8989
          key: 00f4e9053d514e2b8b28a7deb327df78

    - Radarr:
        icon: radarr.png
        href: https://radarr.oukcorp.com/
        description: Movie management
        ping: http://radarr:7878
        container: radarr
        widget:
          type: radarr
          url: http://radarr:7878
          key: c2513cbaba7849f1bcc15cd518df3e76
    - Prowlarr:
        icon: prowlarr.png
        href: https://prowlarr.oukcorp.com/
        ping: http://prowlarr:9696
        container: prowlarr
        widget:
        type: prowlarr
        url: http://prowlarr:9696
        key: 6205b188ff5f4bc7bbab8e657e8f90ca
    - Bazarr:
        icon: bazarr.png
        href: https://bazarr.oukcorp.com/
        ping: http://bazarr:6767
        container: bazarr
        widget:
          type: bazarr
          url: http://bazarr:6767
          key: 09acadca8c25ccd786cc26dc141cf396
    - Qbittorrent:
        icon: qbittorrent.png
        href: https://qb.oukcorp.com/
        ping: http://qbittorrent:8080
        container: qbittorrent
        widget:
          type: qbittorrent
          url: http://qbittorrent:8080
          username: admin
          password: adminadmin


- Oukflix Watch:
    - Jellyfin:
        icon: jellyfin.png
        href: https://jl.oukcorp.com/
        ping: http://jellyfin:8096
        container: jellyfin
        widget:
          type: jellyfin
          url: http://jellyfin:8096
          key: 9539a3e9f06249a3b10a6fc8c702a02b
          enableBlocks: true # optional, defaults to false
          enableNowPlaying: true # optional, defaults to true
    - Jellyseerr:
        icon: jellyseerr.png
        href: https://jsr.oukcorp.com/
        ping: http://jellyseerr:5055
        container: jellyseerr
        widget:
          type: jellyseerr
          url: http://jellyseerr:5055
          key: MTY4ODcyMDk1NzU3MzBhYjc1Yzg5LWJlYzEtNGY3Ny1hNjAyLWM1ZDY0OWZhNzYxNA==

- Monitoring:
    - Portainer:
        icon: portainer.png
        href: https://pr.oukcorp.com/
        ping: http://portainer:9000
        container: portainer
        widget:
          type: portainer
          url: http://portainer:9000
          env: 2
          key: ptr_WYi3p4VeEIWr1TY0vzbneUOkxvS8bwvgdd7TgVqnv0I=

    - Grafana:
        icon: grafana.png
        href: https://grafana.oukcorp.com/
        ping: http://grafana:3000
        container: grafana
        #widget:
        #  type: grafana
        #  url: http://grafana:3000
        #  username: admin
        #  password: &xrX#Xyh@UBun3MLc28Yia9jW6L^VR

    - Traefik:
        icon: traefik.png
        href: https://traefik.oukcorp.com/
        #ping: http://traefik:8080
        container: traefik
        #widget:
        #  type: traefik
        #  url: http://traefik:8080

    - Kuma:
        icon: uptime-kuma.png
        href: https://kuma.oukcorp.com
        ping: http://uptime-kuma:3001
        container: uptime-kuma

- Self-Host:
    - Pi-Hole:
        icon: pi-hole.png
        href: https://pi.oukcorp.com/
        ping: http://pihole:80
        container: pihole
        widget:
          type: pihole
          url: http://pihole:80
          key: 458f77e2c27c00cac7f1710e8ff1be5964030bc176dbf29c9c215a876489ddd5 # optional
    - Nextcloud:
        icon: nextcloud.png
        href: https://nextcloud.oukcorp.com/
        ping: http://nextcloud:443
        container: nextcloud
        #widget:
        #  type: nextcloud
        #  url: http://nextcloud:443
        #  username: Fencing7589
        #  password: 7ah@jahB2#5*%m7EM#C%F7QXYETXJZ
    - Vaultwarden:
        icon: vaultwarden.png
        href: https://vw.oukcorp.com/
        ping: http://vaultwarden:80
        container: vaultwarden

